name: askingucu
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  animated_text_kit: ^4.2.1
  simple_icons: ^6.13.0
 
  slide_drawer: ^1.0.3
  flutter_zoom_drawer: ^2.1.2

  validators: ^3.0.0
  motion_toast: ^2.1.6
  public_suffix: ^1.2.1
  page_transition: "^2.0.4"
  flutter_launcher_icons: ^0.9.2
  curved_navigation_bar: ^1.0.1
  form_field_validator: ^1.1.0
  localization: ^2.1.0
  version: ^2.0.0
  google_fonts: ^3.0.1
  dio: ^4.0.4
  async: ^2.8.2
  flutter_speed_dial: ^5.0.0+1
  http: ^0.13.3
  shared_preferences: ^2.0.13
  webview_flutter: ^3.0.2
  json_serializable_dart: ^1.0.1
  getwidget: ^2.0.4
  story_view: ^0.13.2
  video_player: ^2.4.7
 
  get: ^4.6.1
  firebase_messaging: ^13.0.1
  firebase_core: ^1.23.0 
  firebase_performance: ^0.8.2+4
  firebase_crashlytics: ^2.8.9
  firebase_remote_config: ^2.0.6
  firebase_device_id: ^0.0.3
 
  flutter_local_notifications: ^9.0.0
  get_version: ^0.2.2
  cherry_toast: ^1.0.6

  kt_drawer_menu: ^0.0.6
  client_information: ^2.0.2+2
  url_launcher: ^6.0.18
  file_picker: ^4.3.3
  
  flutter_advanced_drawer: ^1.2.4
  iconsax: ^0.0.8
  loading_indicator: ^3.0.2
  avatar_glow: ^2.0.1
  connectivity_plus: ^2.2.0
  no_internet_check: ^1.0.0
  flutter_easyloading: ^3.0.3
  flutter_svg: ^0.22.0

  material_dialogs: ^1.1.1
 
  flutter_slidable: ^1.2.0
  simple_animations: ^1.3.3
  
  flutter_spinkit: ^5.1.0
  z_dialog: ^1.1.2
  ionicons: ^0.1.2
  flutter_downloader: ^1.7.2
  loading_animation_widget: ^1.1.0+3

  awesome_page_transitions: ^1.0.0
  page_animation_transition: ^0.0.9
 
  onesignal_flutter: ^3.3.0
  text_scroll: ^0.0.4
  change_app_package_name: ^1.0.0
  lottie: ^1.3.0
  awesome_bottom_navigation: ^0.0.4

  marquee: ^2.2.1
  new_version: ^0.2.0
  intl: ^0.17.0
  animations: ^2.0.2

  flutter_animate: ^2.0.0
  neon_widgets: ^0.1.2
  animated_splash_screen: ^1.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/img/logo.svg
    - assets/img/logo.png
    - assets/img/go.png
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
